import os
import time
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import BaseCallback, EvalCallback, CheckpointCallback, CallbackList
from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.utils import set_random_seed
from stable_baselines3.common import results_plotter

# ----------------------------------------------------------------
# IMPORT YOUR ENVIRONMENT
# ----------------------------------------------------------------
from rocket_env.rocket_landing_env_new import RocketLandingEnv

# ======================================================================
#   HELPER: PLOTTING
# ======================================================================
def plot_training_results(log_dir, run_name):
    """
    Reads the monitor.csv files generated by SB3 and plots the learning curve.
    """
    print(f"\n📊 Generating training plots in {log_dir}...")
    
    # SB3 Monitor logs are usually named 0.monitor.csv, 1.monitor.csv etc.
    # We use the helper from SB3 to load them into a Dataframe
    try:
        df = results_plotter.load_results(log_dir)
    except IndexError:
        print("⚠️ No monitor data found. Did the training run long enough?")
        return

    if len(df) < 10:
        print("⚠️ Not enough data points to plot yet.")
        return

    # Sort by time
    df = df.sort_values("t")
    
    # Calculate rolling window for smoothing
    window_size = max(10, len(df) // 20) # dynamic window
    df["reward_smooth"] = df["r"].rolling(window=window_size).mean()
    df["len_smooth"] = df["l"].rolling(window=window_size).mean()

    # Create Plot
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), sharex=True)
    
    # 1. Rewards
    ax1.set_title(f"Training Progress: {run_name}")
    ax1.plot(df["t"], df["r"], color="lightblue", alpha=0.3, label="Raw Reward")
    ax1.plot(df["t"], df["reward_smooth"], color="blue", linewidth=2, label=f"Smoothed (MA {window_size})")
    ax1.set_ylabel("Episodic Reward")
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # 2. Episode Lengths
    ax2.plot(df["t"], df["l"], color="lightgreen", alpha=0.3)
    ax2.plot(df["t"], df["len_smooth"], color="green", linewidth=2, label="Episode Length")
    ax2.set_ylabel("Steps per Episode")
    ax2.set_xlabel("Timesteps")
    ax2.grid(True, alpha=0.3)

    # Save
    save_path = os.path.join(log_dir, "training_curve.png")
    plt.tight_layout()
    plt.savefig(save_path)
    print(f"✅ Plot saved to: {save_path}")
    plt.close()

# ======================================================================
#   CALLBACK: VISUALIZE PERIODICALLY
# ======================================================================
class VisualizeCallback(BaseCallback):
    def __init__(self, check_freq: int, verbose=1):
        super().__init__(verbose)
        self.check_freq = check_freq
        self.test_env = None

    def _on_step(self) -> bool:
        if self.n_calls % self.check_freq == 0:
            print(f"\n👀 Visualizing policy at step {self.num_timesteps}...")
            if self.test_env is None:
                self.test_env = RocketLandingEnv(render_mode="human")
            
            obs, _ = self.test_env.reset()
            total_reward = 0.0
            success = False
            
            for _ in range(2000): 
                action, _ = self.model.predict(obs, deterministic=True)
                obs, reward, terminated, truncated, info = self.test_env.step(action)
                self.test_env.render()
                time.sleep(0.005)
                total_reward += reward
                if terminated or truncated:
                    success = info.get("success", False)
                    break
            
            status = "\033[92m✅ SUCCESS\033[0m" if success else "\033[91m❌ FAILURE\033[0m"
            print(f"   Result: {status} | Total Reward: {total_reward:.2f}")
            print("-" * 40)
        return True

# ======================================================================
#   ENV FACTORY
# ======================================================================
def make_env(rank: int, seed: int, log_dir: str):
    """
    Utility function for multiprocessed env.
    IMPORTANT: We pass log_dir here so Monitor() writes the CSVs needed for plotting.
    """
    def _init():
        env = RocketLandingEnv(render_mode=None)
        # Create unique log file for this worker
        log_file = os.path.join(log_dir, str(rank)) if log_dir else None
        env = Monitor(env, filename=log_file) 
        env.reset(seed=seed + rank)
        return env
    return _init

# ======================================================================
#   ARGUMENT PARSER
# ======================================================================
def parse_args():
    parser = argparse.ArgumentParser(description="PPO Training for Rocket Landing")
    parser.add_argument("--timesteps", type=int, default=5_000_000, help="Total training timesteps")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument("--lr", type=float, default=3e-4, help="Learning rate")
    parser.add_argument("--batch_size", type=int, default=64, help="Batch size")
    parser.add_argument("--n_steps", type=int, default=2048, help="Steps per update")
    parser.add_argument("--ent_coef", type=float, default=0.01, help="Entropy coefficient")
    parser.add_argument("--gamma", type=float, default=0.99, help="Discount factor")
    parser.add_argument("--net_arch", type=int, nargs="+", default=[256, 256], help="Hidden layers")
    parser.add_argument("--save_freq", type=int, default=100_000, help="Save checkpoint frequency")
    parser.add_argument("--eval_freq", type=int, default=50_000, help="Eval frequency")
    parser.add_argument("--vis_freq", type=int, default=100_000, help="Visualize frequency")
    return parser.parse_args()

# ======================================================================
#   MAIN TRAINING
# ======================================================================
def train():
    args = parse_args()
    
    # 1. Setup Directories
    run_name = f"ppo_rocket_{time.strftime('%Y-%m-%d_%H-%M-%S')}"
    base_dir = "runs"
    log_dir = os.path.join(base_dir, run_name)
    os.makedirs(log_dir, exist_ok=True)
    
    print(f"\n🚀 INITIALIZING PPO TRAINING: {run_name}")
    print(f"   Hyperparams: {vars(args)}")
    print(f"   Logging to: {log_dir}\n")

    set_random_seed(args.seed)

    # 2. Create Vectorized Environment
    # We pass log_dir to make_env so Monitor saves data for plotting
    env = DummyVecEnv([make_env(rank=0, seed=args.seed, log_dir=log_dir)])
    env = VecNormalize(env, norm_obs=True, norm_reward=True, clip_obs=10., gamma=args.gamma)

    # 3. Create Evaluation Environment
    # Helper for eval env (doesn't need to log to CSV, but needs to exist)
    eval_log_dir = os.path.join(log_dir, "eval_logs")
    os.makedirs(eval_log_dir, exist_ok=True)
    
    eval_env = DummyVecEnv([make_env(rank=1, seed=args.seed, log_dir=None)])
    eval_env = VecNormalize(eval_env, norm_obs=True, norm_reward=False, clip_obs=10., gamma=args.gamma)
    eval_env.training = False 
    eval_env.norm_reward = False

    # 4. Define Callbacks
    eval_callback = EvalCallback(
        eval_env,
        best_model_save_path=os.path.join(log_dir, "best_model"),
        log_path=eval_log_dir, # Saves evaluations.npz here
        eval_freq=args.eval_freq,
        n_eval_episodes=10,
        deterministic=True,
        render=False
    )
    
    checkpoint_callback = CheckpointCallback(
        save_freq=args.save_freq,
        save_path=os.path.join(log_dir, "checkpoints"),
        name_prefix="ppo_rocket"
    )

    visual_callback = VisualizeCallback(check_freq=args.vis_freq)
    callback_list = CallbackList([eval_callback, checkpoint_callback, visual_callback])

    # 5. Define Model
    policy_kwargs = dict(net_arch=dict(pi=args.net_arch, vf=args.net_arch))
    model = PPO(
        "MlpPolicy",
        env,
        verbose=1,
        policy_kwargs=policy_kwargs,
        learning_rate=args.lr,
        n_steps=args.n_steps,       
        batch_size=args.batch_size,     
        n_epochs=10,        
        gamma=args.gamma,
        gae_lambda=0.95,
        clip_range=0.2,
        ent_coef=args.ent_coef,      
        tensorboard_log=os.path.join(log_dir, "tb_logs"),
        device="auto"
    )

    # 6. Train
    try:
        model.learn(
            total_timesteps=args.timesteps, 
            callback=callback_list,
            progress_bar=True
        )
    except KeyboardInterrupt:
        print("\n⚠️ Training interrupted manually.")

    # 7. Wrap up
    print("\n✅ Saving final model...")
    model.save(os.path.join(log_dir, "final_model"))
    env.save(os.path.join(log_dir, "vec_normalize.pkl"))
    
    env.close()
    eval_env.close()
    
    # 8. PLOT RESULTS
    plot_training_results(log_dir, run_name)
    print("Done.")

if __name__ == "__main__":
    train()